# Generated by Django 5.0.6 on 2024-07-24 14:13

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_productgallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
