# Generated by Django 5.0.6 on 2024-07-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productgallery_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='cropping',
        ),
    ]
