# Generated by Django 5.0.6 on 2024-08-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.FloatField(default=0),
        ),
    ]
