# Generated by Django 5.0.6 on 2024-08-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_offer_percentage_product_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.IntegerField(default=0),
        ),
    ]
