# Generated by Django 5.0.6 on 2024-07-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_order_orderitem_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
