# Generated by Django 5.0.6 on 2024-07-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_cart_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.IntegerField(),
        ),
    ]
