# Generated by Django 5.0.6 on 2024-07-30 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_alter_coupon_discount_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='discount',
        ),
    ]
