# Generated by Django 5.0.6 on 2024-07-30 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_cart_discount_coupon_cart_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carts.cart')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.coupon')),
            ],
        ),
    ]
