# Generated by Django 5.0.6 on 2024-08-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0015_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
