# Generated by Django 5.0.6 on 2024-07-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
