# Generated by Django 5.0.6 on 2024-08-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_offer_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='offer_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
