# Generated by Django 5.0.6 on 2024-07-22 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_order_order_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
