# Generated by Django 5.0.6 on 2024-07-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_coupon_valid_from_remove_coupon_valid_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
