# Generated by Django 5.0.6 on 2024-08-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
