# Generated by Django 5.0.6 on 2024-08-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
